# irec.pl --
#
# angelos@unix.gr
#
# UI generated by GUI Builder Build 146 on 2009-01-26 14:40:50 from:
#    C:/Documents and Settings/akarageorgiou/Desktop/Perl Code/irec.ui
# This file is auto-generated.  Only the code within
#    '# BEGIN USER CODE'
#    '# END USER CODE'
# and code inside the callback subroutines will be round-tripped.
# The subroutine name 'ui' is reserved.
#

# Declare the package for this dialog
package irec;

# BEGIN USER CODE
use Win32::SoundRec;
use Win32::Sound;
use File::Copy;
use Tk;
use Tk::Menu;


my $r =  Win32::SoundRec->new();

my $RECORDING=0;
my $STOPPED=1;
my $WAVfile="SoundRec.wav";
########################################################################
sub startrec {
	return if ( $RECORDING);
	$RECORDING=1;
	$STOPPED=0;
	$isactive="Start singing"; 
	$_button_3->configure( -state => 'disabled');
	$_button_4->configure( -state => 'disabled');
	$r->record();
}

########################################################################
sub stoprec {
	return if ( $STOPPED == 1);
	$RECORDING=0;
	$STOPPED=1;
		$r->stop();
		$r->save($WAVfile);
	$isactive="";
	$_button_3->configure( -state => 'active');
	$_button_4->configure( -state => 'active');
}


########################################################################
sub replay {
	$RECORDING=1;
	Win32::Sound::Play($WAVfile);
	$RECORDING=0;
}


########################################################################
sub savefile {

	my $filename = $top->getSaveFile( 
	-title => 'Save Recording:',
    	-defaultextension => '.wav',
	-initialfile => 'irene.wav', 
	-filetypes => [
		[ 'Sound Files' => '.wav' ],
		[ 'All files' => '*' ],
	],
 	);

if ( $filename ) { copy($WAVfile,$filename); }
}

########################################################################

sub irec::ui {
    our($root) = @_;


    # Widget Initialization
    our($_button_1) = $root->Button(
	-activebackground => "#00ffff",
	-background => "#009900",
	-font => '{MS Sans Serif} 12 bold',
	-highlightcolor => "#000000",
	-text => "Record me",
    );
    our($_button_2) = $root->Button(
	-background => "#ff0000",
	-font => '{Franklin Gothic Medium} 12 bold',
	-text => "I am done",
    );
    our($recording) = $root->Label(
	-font => '{Curlz MT} 14',
	-text => "Trivial Sound Recorder",
    );
    our($_label_2) = $root->Label(
	-font => '{Franklin Gothic Medium} 12 bold',
	-text => "Cool PERL examples on Win32\nangelos\@unix.gr",
    );
    our($_label_3) = $root->Label(
	-activeforeground => "#009900",
	-font => '{MS Sans Serif} 19',
	-text => "_label_3",
	-textvariable => \$isactive,
    );
    our($_button_3) = $root->Button(
	-font => '{MS Sans Serif} 10',
	-state => "disabled",
	-text => "Lemme Hear Myself",
    );
    our($_button_4) = $root->Button(
	-font => '{MS Sans Serif} 11',
	-state => "disabled",
	-text => "Save my voice for posterity",
    );

    # widget commands

    $_button_1->configure(
	-command => \&irec::startrec
    );
    $_button_2->configure(
	-command => \&irec::stoprec
    );
    $_button_3->configure(
	-command => \&irec::replay
    );
    $_button_4->configure(
	-command => \&irec::savefile
    );


    # Geometry Management
    $_button_1->grid(
	-in     => $root,
	-column => 2,
	-row    => 2,
	-columnspan => 1,
	-ipadx => 0,
	-ipady => 0,
	-padx => 0,
	-pady => 0,
	-rowspan => 1,
	-sticky => "s"
    );
    $_button_2->grid(
	-in     => $root,
	-column => 5,
	-row    => 2,
	-columnspan => 1,
	-ipadx => 0,
	-ipady => 0,
	-padx => 0,
	-pady => 0,
	-rowspan => 1,
	-sticky => "n"
    );
    $recording->grid(
	-in     => $root,
	-column => 3,
	-row    => 2,
	-columnspan => 2,
	-ipadx => 0,
	-ipady => 0,
	-padx => 0,
	-pady => 0,
	-rowspan => 1,
	-sticky => ""
    );
    $_label_2->grid(
	-in     => $root,
	-column => 2,
	-row    => 1,
	-columnspan => 4,
	-ipadx => 0,
	-ipady => 0,
	-padx => 0,
	-pady => 0,
	-rowspan => 1,
	-sticky => ""
    );
    $_label_3->grid(
	-in     => $root,
	-column => 3,
	-row    => 3,
	-columnspan => 2,
	-ipadx => 0,
	-ipady => 0,
	-padx => 0,
	-pady => 0,
	-rowspan => 1,
	-sticky => ""
    );
    $_button_3->grid(
	-in     => $root,
	-column => 3,
	-row    => 4,
	-columnspan => 1,
	-ipadx => 0,
	-ipady => 0,
	-padx => 0,
	-pady => 0,
	-rowspan => 1,
	-sticky => ""
    );
    $_button_4->grid(
	-in     => $root,
	-column => 4,
	-row    => 4,
	-columnspan => 1,
	-ipadx => 0,
	-ipady => 0,
	-padx => 0,
	-pady => 0,
	-rowspan => 1,
	-sticky => ""
    );


    # Resize Behavior
    $root->gridRowconfigure(1, -weight => 0, -minsize => 40, -pad => 0);
    $root->gridRowconfigure(2, -weight => 0, -minsize => 40, -pad => 0);
    $root->gridRowconfigure(3, -weight => 0, -minsize => 40, -pad => 0);
    $root->gridRowconfigure(4, -weight => 0, -minsize => 40, -pad => 0);
    $root->gridRowconfigure(5, -weight => 0, -minsize => 40, -pad => 0);
    $root->gridColumnconfigure(1, -weight => 0, -minsize => 40, -pad => 0);
    $root->gridColumnconfigure(2, -weight => 0, -minsize => 40, -pad => 0);
    $root->gridColumnconfigure(3, -weight => 0, -minsize => 2, -pad => 0);
    $root->gridColumnconfigure(4, -weight => 0, -minsize => 2, -pad => 0);
    $root->gridColumnconfigure(5, -weight => 0, -minsize => 40, -pad => 0);
    $root->gridColumnconfigure(6, -weight => 0, -minsize => 40, -pad => 0);
}

irec::userinit() if defined &irec::userinit;

our $top = MainWindow->new();
$top->title("irec");
irec::ui($top);

irec::run() if defined &irec::run;

Tk::MainLoop();

1;
