#!//usr/bin/perl --

#
# Database generator, input are the   files Generated by Xray
#
# Nov 2001 Angelos Karageorgiou
#

use DB_File;
use Fcntl;

require POSIX;
$loc=POSIX::setlocale(&POSIX::LC_CTYPE,"ISO8859-7");
use locale;

tie %DOMHASH,"DB_File","domains.db";

open(FILE,"<domains_scanned") ||  die "No domain file";
print "Reading scanned domains\n";
$i=0;
while(<FILE>) {
	print $i++ . "\r";
	chomp($_);
	($domain,$software,$ip)=split(':',$_);
	$domain=~s/www\.//;

	$IP{$domain}=$ip;
	$SOFT{$domain}=$software;
}
close(FILE);

open(FILE,"<domains_per_server") ||  die "No domain file";
print "\n\nReading dns file\n";
$i=0;

while(<FILE>) {
	print $i++ . "\r";
        ($dom,$server)=split("\t",$_);
	chomp($server);

	if ( ! $DOMHASH{$dom} ) {
		$DOMHASH{$dom} = $IP{$dom} . ":" . $SOFT{$dom} . ":" . $server;
	} else {
		$DOMHASH{$dom} .= ",$server";
	}
}

close(FILE);


untie %DOMHASH;
print "\n\n";
